#!/bin/bash
#
# Joseph's Ubuntu Server Banner MOTD v1.2.1
# 51-joseph-motd[.sh]
#
# [Installation]
#     1. Please put this file to /etc/update-motd.d 
#     2. Give *+x permission
#
# [About IP Lookup]
#     By default this script uses a HTTP request that returns only one IP address with text/plain to
#     lookup local IP address. Another way is use HTTPDNS.
#         __JMOTD_LOOPUP_IP_DNS=1 ;USE HTTPDNS
#         __JMOTD_LOOPUP_IP_DNS=0 ;USE HTTP Request
#     If you want to change it in command line, use: (51-joseph-motd is filename of this script)
#         sed -i "s/^__JMOTD_LOOPUP_IP_DNS=0$/__JMOTD_LOOPUP_IP_DNS=1/g" 51-joseph-motd

__JMOTD_VER="1.2.1"
__JMOTD_LOOPUP_IP_DNS=0
__JMOTD_LOOPUP_IP_HTTPDNSS="http://119.29.29.29/d?dn=$(hostname)"
__JMOTD_LOOPUP_IP_NCSIADDR="https://ncsi.josephcz.xyz/ip.php"

if [ $__JMOTD_LOOPUP_IP_DNS == 1 ]; then
	__JMOTD_LOOPUP_IP_RES=`curl -s $__JMOTD_LOOPUP_IP_HTTPDNSS`
else
	__JMOTD_LOOPUP_IP_RES=`curl -s $__JMOTD_LOOPUP_IP_NCSIADDR`
fi

echo "  "Memory Usage: `free -h | grep Mem | awk '{print $3}'`B/`free -h | grep Mem | awk '{print $2}'`B
echo "  "Swap Usage:"   "`free -h | grep Swap | awk '{print $3}'`B/`free -h | grep Swap | awk '{print $2}'`B
echo "  "Boot Time:"    "`uptime -s`
echo "  "Current Time:" "`date +"%Y-%m-%d %H:%M:%S %Z"`
echo "  "Uptime:"       "`uptime -p | cut -c4-`
echo "  "Public IP:"    $__JMOTD_LOOPUP_IP_RES"
echo "  "Hostname:"     "`hostname`
echo "  "CPU Model:"   "`cat /proc/cpuinfo | grep "model name" | cut -d":" -f2 | head -n 1`
