#!/bin/bash
# VPS Info Banner v1.2.7
# [LICENSE] MIT License / GPL 3.0+ / 01PL-2.0
# [INSTALL] curl https://lty.name/vpsinfo -o /etc/update-motd.d/51-vps-info && chmod +x /etc/update-motd.d/51-vps-info

LANG=en
#IP=$(curl -sf "https://ncsi.josephcz.xyz/ip")
#IP=$(curl -sf "http://119.29.29.29/d?dn=$(cat /etc/hostname)")
IP=$(dig +short $(cat /etc/hostname) @1.1.1.1)
CPU=$(lscpu | grep "^Model name" | head -1 | cut -d":" -f2 | xargs)
NCPU=$(lscpu | grep "^CPU(s):" | head -1 | cut -d":" -f2 | xargs)

echo ""
echo "  CPU Model:     " "$CPU ($NCPU)"
echo "  Memory Usage:  " `free -m | grep Mem | awk '{print $3}'`MiB/`free -m | grep Mem | awk '{print $2}'`MiB
echo "  Swap Usage:    " `free -m | grep Swap | awk '{print $3}'`MiB/`free -m | grep Swap | awk '{print $2}'`MiB
echo "  Boot Time:     " `uptime -s`
echo "  Current Time:  " `date +"%Y-%m-%d %H:%M:%S %Z"`
echo "  Uptime:        " `uptime -p | cut -c4-`
echo "  Public IP:     " "$IP"
echo "  Hostname:      " `hostname`
echo ""
