#!/bin/bash
# VPS Info Banner v1.3.1
# [LICENSE] MIT License / GPL 3.0+ / 01PL-2.0
# [INSTALL] curl https://lty.name/vpsinfo -o /etc/update-motd.d/51-vps-info && chmod +x /etc/update-motd.d/51-vps-info

LANG=en
#IP=$(curl -sf --connection-timeout 5 "https://ncsi.josephcz.xyz/ip")
IP=$(dig +time=5 +retry=1 +tries=1 +short $(cat /etc/hostname) @1.1.1.1)
CPU=$(lscpu | grep "^Model name" | head -1 | cut -d":" -f2 | xargs)
NCPU=$(lscpu | grep "^CPU(s):" | head -1 | cut -d":" -f2 | xargs)

echo ""
echo "  CPU Model:     " "$CPU ($NCPU)"
echo "  Memory Usage:  " `free -m | grep Mem | awk '{print $3}'`MiB/`free -m | grep Mem | awk '{print $2}'`MiB
echo "  Swap Usage:    " `free -m | grep Swap | awk '{print $3}'`MiB/`free -m | grep Swap | awk '{print $2}'`MiB
echo "  Current Time:  " `date +"%Y-%m-%d %H:%M:%S %Z"`
if [ "$(uptime --version | grep -c procps)" == "0" ]; then
	# Fix for openSUSE
	echo "  Uptime:        " `uptime | cut -d, -f1 | cut -d" " -f5-`
else
	echo "  Boot Time:     " `uptime -s`
	echo "  Uptime:        " `uptime -p | cut -c4-`
fi
echo "  Public IP:     " "$IP"
echo "  Hostname:      " `hostname`
echo ""

