#!/bin/bash
# debian-nginx-inst - v1.0.0
# Copyight (c) 2025 Joseph Chris <joseph@josephcz.xyz> under MIT License
#
# Copy available at lty.vc/debian-nginx-inst
#
# Install nginx (full version) on Debian 12/13, configure with
# [github.com/baobao1270/util-scripts]'s edition of configuration,
# with common SSL, OCSP, SNI multi-domain, and management util scripts.
#

set -e

if command -v nginx >/dev/null 2>&1; then
    echo "Nginx is installed. Exit."
    exit 2
fi

apt-get install -y nginx-full
rm -rf /tmp/github.com-baobao1270-util-scripts
git clone https://github.com/baobao1270/util-scripts /tmp/github.com-baobao1270-util-scripts
rm -rvf /etc/nginx/sites-available
mv -v   /tmp/github.com-baobao1270-util-scripts/nginx/* /etc/nginx
cd /etc/nginx
sed  -i '/^#/d'               /etc/nginx/nginx.conf
sed  -i '/http {/,/}/d;/^$/d' /etc/nginx/nginx.conf
cat <<EOF >> /etc/nginx/nginx.conf
http {
	include /etc/nginx/http.conf;
	include /etc/nginx/sites-enabled/*;
}
EOF
# https://ssl-config.mozilla.org/ffdhe2048.txt
cat <<EOF > /etc/ssl/dhparam
-----BEGIN DH PARAMETERS-----
MIIBCAKCAQEA//////////+t+FRYortKmq/cViAnPTzx2LnFg84tNpWp4TZBFGQz
+8yTnc4kmz75fS/jY2MMddj2gbICrsRhetPfHtXV/WVhJDP1H18GbtCFY2VVPe0a
87VXE15/V8k1mE8McODmi3fipona8+/och3xWKE2rec1MKzKT0g6eXq8CrGCsyT7
YdEIqUuyyOP7uWrat2DX9GgdT0Kj3jlN9K5W7edjcrsZCwenyO4KbXCeAvzhzffi
7MA0BM0oNC9hkXL+nOmFg/+OTxIy7vKBg8P+OxtMb61zO7X8vC7CIAXFjvGDfRaD
ssbzSibBsu/6iGtCOGEoXJf//////////wIBAg==
-----END DH PARAMETERS-----
EOF
curl -L lty.vc/ngxcmd | bash -s update
